import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../models/poi_model.dart';

/// Loads the demo's OSM-sourced points of interest from the bundled
/// `assets/data/pois.json` asset (generated by `tool/fetch_pois.dart`).
///
/// The app never calls Overpass at runtime — see the goal spec's
/// reliability requirement — so this service only ever reads the local
/// asset. It surfaces load failures (missing/malformed asset) as a thrown
/// [PoiLoadException] rather than silently returning an empty list, so the
/// UI can show a visible-but-non-blocking error state per the acceptance
/// criteria, instead of a confusingly empty map.
class PoiService {
  static final PoiService _instance = PoiService._internal();
  factory PoiService() => _instance;
  PoiService._internal();

  static const String _assetPath = 'assets/data/pois.json';

  List<Poi>? _cache;

  /// Loads and caches the POI list. Safe to call repeatedly; subsequent
  /// calls return the cached list without re-reading the asset.
  Future<List<Poi>> loadPois() async {
    final cached = _cache;
    if (cached != null) return cached;

    try {
      final raw = await rootBundle.loadString(_assetPath);
      final parsed = jsonDecode(raw) as Map<String, dynamic>;
      final poisJson = (parsed['pois'] as List).cast<Map<String, dynamic>>();
      final pois = poisJson.map(Poi.fromJson).toList();
      _cache = pois;
      return pois;
    } catch (e) {
      throw PoiLoadException(
        'Could not load points of interest. Please try again later.',
        cause: e,
      );
    }
  }

  /// Clears the cache, forcing the next [loadPois] call to re-read the
  /// asset. Mainly useful for tests.
  void clearCache() => _cache = null;
}

/// Thrown when `assets/data/pois.json` is missing or malformed.
class PoiLoadException implements Exception {
  final String message;
  final Object? cause;

  const PoiLoadException(this.message, {this.cause});

  @override
  String toString() => 'PoiLoadException: $message';
}
